name: transformer-architecture
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python
  - torchaudio
  - pytorch
  - torchvision
  - cpuonly
  - transformers
  - jupyterlab
  - ipywidgets
  - ipympl
  - tqdm
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip
  - pip:
      - accelerate
